# Use the official Node.js image as the base image
FROM node:18


# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app will run on
EXPOSE 6001

# Copy and run the script
COPY ./scripts/run_app_dev.sh /app/scripts/run_app_dev.sh
RUN chmod +x /app/scripts/run_app_dev.sh

CMD ["/bin/sh", "-c", "/app/scripts/run_app_dev.sh"]
